name: publish
on: push

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Use nightly rust
        run: rustup override set nightly

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-pypi.txt

      - name: Build
        run: maturin build

      - name: Secret test
        run: echo ${{secrets.PYPI_USERNAME}}

      - name: Publish
        run: maturin publish -u ${{secrets.PYPI_USERNAME}} -p ${{secrets.PYPI_PASSWORD}} --interpreter=3.8