on: [push]
name: tests

jobs:
  test:
    name: tests
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master

      - name: Use nightly rust
        run: rustup override set nightly

      - uses: actions/checkout@v2

      - name: Run tests
        run: cargo test
