name: Publish
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use nightly rust
        run: rustup override set nightly

      - name: Install cargo-tarpaulin for coverage
        run: cargo install cargo-tarpaulin

      - uses: actions/checkout@v2
      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test

      - name: Generate xml
        run: cargo tarpaulin --out Xml

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}} && echo "Uploaded code coverage"

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-pypi.txt

      - name: Publish
        run: maturin publish -u ${{secrets.PYPI_USERNAME}} -p ${{secrets.PYPI_PASSWORD}}