on: [push]
name: Pipeline

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/checkout@v2
      - name: Install Rust latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install Cargo-Tarpaulin (coverage)
        run: cargo install cargo-tarpaulin

      - name: Test
        run: cargo test

      - name: Generate XML
        run: cargo tarpaulin --out Xml

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}} && echo "Uploaded code coverage"

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-pypi.txt

      - name: Publish
        run: maturin publish -o -u ${{secrets.PYPI_USERNAME}} -p ${{secrets.PYPI_PASSWORD}}